// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANVNojc3XwRxhmI9pJsoWukptn638tRmM',
    appId: '1:167673247748:web:0874608adb99df24ef5d51',
    messagingSenderId: '167673247748',
    projectId: 'leothaptuvung',
    authDomain: 'leothaptuvung.firebaseapp.com',
    storageBucket: 'leothaptuvung.firebasestorage.app',
    measurementId: 'G-46R85T1RYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjSJMSrIba8g9MO4t8dBXWVrRXhSjdHgQ',
    appId: '1:167673247748:android:c786e08027a51d63ef5d51',
    messagingSenderId: '167673247748',
    projectId: 'leothaptuvung',
    storageBucket: 'leothaptuvung.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_2NQ9y2baIdFgaIBkfNLpVAbVuqz994M',
    appId: '1:167673247748:ios:1b972547aa123d04ef5d51',
    messagingSenderId: '167673247748',
    projectId: 'leothaptuvung',
    storageBucket: 'leothaptuvung.firebasestorage.app',
    iosBundleId: 'com.example.leoThapTuVung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_2NQ9y2baIdFgaIBkfNLpVAbVuqz994M',
    appId: '1:167673247748:ios:1b972547aa123d04ef5d51',
    messagingSenderId: '167673247748',
    projectId: 'leothaptuvung',
    storageBucket: 'leothaptuvung.firebasestorage.app',
    iosBundleId: 'com.example.leoThapTuVung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANVNojc3XwRxhmI9pJsoWukptn638tRmM',
    appId: '1:167673247748:web:3051ea73f255e4e2ef5d51',
    messagingSenderId: '167673247748',
    projectId: 'leothaptuvung',
    authDomain: 'leothaptuvung.firebaseapp.com',
    storageBucket: 'leothaptuvung.firebasestorage.app',
    measurementId: 'G-Y476NLJYHR',
  );
}
